### ISSUE TITLE
System.FormatException: Invalid length for a Base-64 char array or string

### ISSUE THREAD

**Issue by BrownMax** [NotSoSecure/Blacklist3r#12]
I get these errors even on using previous and latest releases. 

The command I used is :- 
`AspDotNetWrapper.exe --keypath MachineKeys.txt --encrypteddata /wEPDwUKLTg0MzcxNzgzNmQYAQUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgIFJmN0bDAwJENvbnElbnRQbGFjZUhvbGRicjEkSW1hZ2VCdXR0b24zBSZjdGwwMCRDb2250ZW50UGxhY2Vlb2xkZXlxJEltYWdlQnV0dG9uMU3je+cjx5/7z0zvwlrr8SPmt2y8== --decrypt --purpose=viewstate --modifier=CA0B0334 --macdecode --IISDirPath "/" --TargetPagePath "/Default.aspx/" -f out.txt
`

And got these errors :- 
`
Unhandled Exception: System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at NotSoSecure.AspDotNetWrapper.DefinePurpose.GetProtectedData(String strEncryptedText)
   at NotSoSecure.AspDotNetWrapper.AspDotNetWrapper.Main(String[] args)
`
Please note that the value of viewstate didn't contained  "==". I added them by reading a post on [StackOverFlow](https://stackoverflow.com/questions/43601994/system-formatexception-invalid-length-for-a-base-64-char-array-or-string) . But still got no luck with the errors.

**Comment by devsecboy** [comment]
Hello,

I have validated the base64 string against "https://base64.guru/tools/repair" tool

which state that the base64 data which is supplied in above command is malformed and below is the original form of base64

/wEPDwUKLTg0MzcxNzgzNmQYAQUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgIFJmN0bDAwJENvbnElbnRQbGFjZUhvbGRicjEkSW1hZ2VCdXR0b24zBSZjdGwwMCRDb2250ZW50UGxhY2Vlb2xkZXlxJEltYWdlQnV0dG9uMU3je+cjx5/7z0zvwlrr8SPmt2y

Can you please check and revert?

**Comment by realsanjay** [comment]
@BrownMax 
 
Closing the issue due to inactivity if the issue still persists, please feel free to open a new issue

**Comment by devsecboy** [comment]
@BrownMax 
 
Closing the issue due to inactivity if the issue still persists, please feel free to open a new issue
