### ISSUE TITLE
question

### ISSUE THREAD

**Issue by mahsamansuri** [NotSoSecure/Blacklist3r#14]
Hello ,,
thank you very much for this software.
Does Blacklist3r for ViewState produced with (.Net < 4.5 and EnableViewStateMac=true/false and ViewStateEncryptionMode=true ) work?
And that legacy is unknown in Blacklist3r.

**Comment by devsecboy** [comment]
@mahsamansuri 
currently the tool doesn't support this particular case.

**Comment by mahsamansuri** [comment]
thank you for your answer.

**Comment by mahsamansuri** [comment]
> @mahsamansuri
> currently the tool doesn't support this particular case.

thank you for your answer.
