### ISSUE TITLE
Encrypted data is too long for command prompt.

### ISSUE THREAD

**Issue by aab641** [NotSoSecure/Blacklist3r#5]
Hi,

My encrypted data is 9359 chars. Command prompt only allows 8191 chars. I think there should be a parameter for --encrypteddata that takes a filepath, such as --encrypteddatapath where the program can take the encrypted data from a text file. Very cool program!

Best,
Alex

**Comment by devsecboy** [comment]
It's check for file existence for the supplied value in --encrypteddata, If the file path supplied to --encrypteddata then application read the encrypted data from file, else it will assume that the data passed in --encrypteddata is the actual encrypteddata.
