### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by dginsburg94** [NotSoSecure/Blacklist3r#6]
Please explain how you compile this in visual studio code. Would really help alot!

**Comment by devsecboy** [comment]
If you need the compiled binary, you may download it from https://github.com/NotSoSecure/Blacklist3r/releases -> AspDotNetWrapper.zip

To compile, you may open this solution file "https://github.com/NotSoSecure/Blacklist3r/tree/master/MachineKey/AspDotNetWrapper" in visual studio.
I am using Visual Studio 2017 (community edition)

**Comment by dginsburg94** [comment]
Ok thanks! Like other people mentioned I am getting:

Option 'valalgo' is unknown.
Option 'decalgo' is unknown.
Option 'legacy' is unknown.

I am also using release version 3, which you said fixed the issue. Any ideas?

**Comment by devsecboy** [comment]
In version 3, These are the options removed from the command line, So there is no need to pass these arguments in v3. 

You may find sample command from below document
https://github.com/NotSoSecure/Blacklist3r/blob/master/MachineKey/AspDotNetWrapper/README.md

**Comment by devsecboy** [comment]
Closing the issue due to inactivity if the issue still persists, please feel free to open a new issue
