### ISSUE TITLE
Encryption of Cookie doesn't work

### ISSUE THREAD

**Issue by nallamuthu** [NotSoSecure/Blacklist3r#7]
Decryption of cookie is working but again encrypting the same file is not working(even without any modification)
**Encrypt:** AspDotNetWrapper.exe --keypath MachineKeys.txt -p aspxauth --cookie 490E807FAF8AA1ED00526434900ECBE308314B62C87037458E6F22980208DD7ACAC41DF05D3013D7E91DEE127E4E5A4E2499483B4BD0F5872934BBD5D1C2B81A9054A197  -a SHA1 -b 3DES --decrypt

Decrypt: AspDotNetWrapper.exe -f DecryptedText.txt
**Error:**
EncryptedData
-------------

Unhandled Exception: System.Security.Cryptography.CryptographicException: Specified initialization vector (IV) does not match the block size for this algorithm.
   at System.Security.Cryptography.SymmetricAlgorithm.set_IV(Byte[] value)
   at System.Web.Security.Cryptography.NetFXCryptoService.Protect(Byte[] clearData)
   at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func`2 func, Byte[] input)
   at NotSoSecure.AspDotNetWrapper.EncryptDecrypt.EncryptData(String strDecryptDataFilePath)
   at NotSoSecure.AspDotNetWrapper.AspDotNetWrapper.Main(String[] args)

**Comment by devsecboy** [comment]
@nallamuthu

Can you please test this with the latest release. 
v3.0: https://github.com/NotSoSecure/Blacklist3r/releases/tag/3.0
Sample Commands: https://github.com/NotSoSecure/Blacklist3r/blob/master/MachineKey/AspDotNetWrapper/README.md

**Comment by realsanjay** [comment]
Closing the issue due to inactivity if the issue still persists, please feel free to open a new issue

**Comment by devsecboy** [comment]
@nallamuthu 

Closing the issue due to inactivity if the issue still persists, please feel free to open a new issue.
